apiVersion: v1
kind: ReplicationController
metadata:
  name: pt-income
  labels:
    name: pt-income
spec:
  replicas: 1
  selector:
    name: pt-income
  template:
    metadata:
      labels:
        name: pt-income
    spec:
      containers:
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.1.5
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: LOAD_BALANCER_CIDR
            value: '10.50.0.0/22'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 443
      - name: pt-income
        image: quay.io/ukhomeofficedigital/uk.gov.digital.ho.proving.income.api:${ pt-income-version }
        resources:
          limits:
            cpu: 400m
            memory: 2048Mi
          requests:
            cpu: 200m
            memory: 2048Mi
        env:
          - name: SOME_VALUE
            value: congif
        ports:
          - name: http
            containerPort: 8080