apiVersion: v1
kind: Service
metadata:
  labels:
    name: pt-income
  name: pt-income
spec:
  type: NodePort
  ports:
  - name: https
    port: 443
    containerPort: https
    nodePort: ${ptincome_port}
  selector:
    name: pt-income